- 名称：设置 Node.js 环境
  用途：actions/setup-node@v3.4.1
  和：
    # 在 npmrc 中设置 always-auth。
    always-auth: # 可选，默认为 false
    # 要使用的版本的版本规范。示例：12.x、10.15.1、>=10.15.0。
    节点版本：# 可选
    # 包含要使用的版本的版本规范的文件。示例：.nvmrc、.node-version、.tool-versions。
    节点版本文件：＃可选
    # Node 使用的目标架构。示例：x86、x64。默认使用系统架构。
    架构：#可选
    # 如果您希望操作检查满足版本规范的最新可用版本，请设置此选项。
    检查最新：# 可选
    # 用于设置身份验证的可选注册表。将在项目级别的 .npmrc 和 .yarnrc 文件中设置注册表，并设置身份验证以从 env.NODE_AUTH_TOKEN 读取。
    注册网址：# 可选
    # 针对作用域注册表进行身份验证的可选作用域。使用 GitHub Packages 注册表 (https://npm.pkg.github.com/) 时将回退到存储库所有者。
    范围：#可选
    # 用于从节点版本中提取节点分布。由于存在默认值，因此通常不由用户提供。
    token: # 可选，默认为 ${{ github.token }}
    # 用于指定一个包管理器，用于在默认目录中进行缓存。支持的值：npm、yarn、pnpm。
    缓存：#可选
    # 用于指定依赖文件的路径：package-lock.json、yarn.lock等。支持通配符或文件名列表，用于缓存多个依赖项。
    缓存依赖路径：# 可选
